<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../OptilandWorkbench.InitialStructure.Contracts/OptilandWorkbench.InitialStructure.Contracts.csproj" />
    <ProjectReference Include="../../../../src/OptilandWorkbench.Core/OptilandWorkbench.Core.csproj" />
  </ItemGroup>
</Project>
