using Avalonia.Controls;
using Avalonia.Media;
using OptilandWorkbench.App.Services;

namespace OptilandWorkbench.App.Theming;

internal sealed record ThemePalette(
    Color Surface,
    Color SubtleSurface,
    Color Workspace,
    Color Border,
    Color TextPrimary,
    Color TextSecondary,
    Color TextMuted,
    Color TextDisabled,
    Color TextAccent,
    Color TextOnAccent,
    Color TextWarning,
    Color TextError,
    Color TextSuccess,
    Color Hover,
    Color HoverBorder,
    Color RibbonHover,
    Color RibbonHoverBorder,
    Color RibbonTabHover,
    Color PlotBackground,
    Color PlotText,
    Color PlotTick,
    Color PlotGrid,
    Color PlotAxis,
    Color PlotZeroLine,
    Color PlotHint,
    Color PlotTooltipBackground,
    Color PlotTooltipBorder,
    Color PlotHoverMarkerFill,
    Color PlotBar,
    Color SceneBackground,
    Color SceneBackgroundAlt,
    Color SceneLensFill,
    Color SceneReference,
    Color SceneAxis,
    Color SceneStop,
    Color SceneApertureStop,
    Color SceneSurface,
    Color SceneLensEdge,
    Color SceneTarget,
    Color SceneOrientationFill,
    Color SceneOrientationBorder)
{
    public static ThemePalette Light { get; } = new(
        Surface: Color.FromRgb(250, 250, 252),
        SubtleSurface: Color.FromRgb(242, 242, 247),
        Workspace: Color.FromRgb(220, 223, 228),
        Border: Color.FromRgb(209, 209, 214),
        TextPrimary: Color.FromRgb(32, 34, 38),
        TextSecondary: Color.FromRgb(85, 88, 96),
        TextMuted: Color.FromRgb(110, 114, 124),
        TextDisabled: Color.FromRgb(145, 149, 158),
        TextAccent: Color.FromRgb(0, 102, 204),
        TextOnAccent: Color.FromRgb(255, 255, 255),
        TextWarning: Color.FromRgb(137, 83, 0),
        TextError: Color.FromRgb(181, 38, 30),
        TextSuccess: Color.FromRgb(24, 128, 70),
        Hover: Color.FromRgb(232, 241, 253),
        HoverBorder: Color.FromRgb(174, 204, 239),
        RibbonHover: Color.FromRgb(217, 236, 255),
        RibbonHoverBorder: Color.FromRgb(115, 183, 255),
        RibbonTabHover: Color.FromRgb(235, 246, 255),
        PlotBackground: Color.FromRgb(255, 255, 255),
        PlotText: Color.FromRgb(38, 38, 38),
        PlotTick: Color.FromRgb(80, 80, 80),
        PlotGrid: Color.FromRgb(180, 180, 180),
        PlotAxis: Color.FromRgb(38, 38, 38),
        PlotZeroLine: Color.FromRgb(20, 20, 20),
        PlotHint: Color.FromRgb(110, 110, 115),
        PlotTooltipBackground: Color.FromArgb(226, 35, 35, 38),
        PlotTooltipBorder: Color.FromArgb(150, 255, 255, 255),
        PlotHoverMarkerFill: Color.FromRgb(255, 255, 255),
        PlotBar: Color.FromArgb(190, 31, 145, 94),
        SceneBackground: Color.FromRgb(250, 252, 254),
        SceneBackgroundAlt: Color.FromRgb(229, 235, 243),
        SceneLensFill: Color.FromArgb(104, 105, 151, 185),
        SceneReference: Color.FromRgb(34, 48, 58),
        SceneAxis: Color.FromRgb(134, 146, 166),
        SceneStop: Color.FromRgb(33, 96, 144),
        SceneApertureStop: Color.FromRgb(31, 31, 33),
        SceneSurface: Color.FromRgb(38, 50, 56),
        SceneLensEdge: Color.FromRgb(87, 112, 132),
        SceneTarget: Color.FromRgb(104, 119, 139),
        SceneOrientationFill: Color.FromArgb(214, 255, 255, 255),
        SceneOrientationBorder: Color.FromRgb(120, 132, 147));

    public static ThemePalette DarkOpticStudio { get; } = new(
        Surface: Color.FromRgb(28, 32, 38),
        SubtleSurface: Color.FromRgb(34, 39, 46),
        Workspace: Color.FromRgb(15, 18, 23),
        Border: Color.FromRgb(52, 58, 66),
        TextPrimary: Color.FromRgb(224, 230, 238),
        TextSecondary: Color.FromRgb(178, 186, 198),
        TextMuted: Color.FromRgb(142, 152, 166),
        TextDisabled: Color.FromRgb(104, 114, 129),
        TextAccent: Color.FromRgb(77, 163, 255),
        TextOnAccent: Color.FromRgb(255, 255, 255),
        TextWarning: Color.FromRgb(245, 190, 90),
        TextError: Color.FromRgb(255, 124, 113),
        TextSuccess: Color.FromRgb(98, 211, 138),
        Hover: Color.FromRgb(34, 52, 73),
        HoverBorder: Color.FromRgb(67, 113, 161),
        RibbonHover: Color.FromRgb(25, 61, 99),
        RibbonHoverBorder: Color.FromRgb(62, 135, 214),
        RibbonTabHover: Color.FromRgb(27, 54, 84),
        PlotBackground: Color.FromRgb(17, 22, 28),
        PlotText: Color.FromRgb(224, 230, 238),
        PlotTick: Color.FromRgb(174, 184, 198),
        PlotGrid: Color.FromRgb(55, 64, 76),
        PlotAxis: Color.FromRgb(128, 140, 156),
        PlotZeroLine: Color.FromRgb(204, 214, 226),
        PlotHint: Color.FromRgb(142, 152, 166),
        PlotTooltipBackground: Color.FromArgb(236, 30, 37, 45),
        PlotTooltipBorder: Color.FromArgb(180, 82, 96, 111),
        PlotHoverMarkerFill: Color.FromRgb(17, 22, 28),
        PlotBar: Color.FromArgb(210, 45, 176, 120),
        SceneBackground: Color.FromRgb(15, 20, 26),
        SceneBackgroundAlt: Color.FromRgb(30, 36, 45),
        SceneLensFill: Color.FromArgb(120, 99, 142, 174),
        SceneReference: Color.FromRgb(142, 162, 178),
        SceneAxis: Color.FromRgb(138, 150, 168),
        SceneStop: Color.FromRgb(80, 158, 232),
        SceneApertureStop: Color.FromRgb(214, 222, 232),
        SceneSurface: Color.FromRgb(164, 176, 188),
        SceneLensEdge: Color.FromRgb(116, 142, 164),
        SceneTarget: Color.FromRgb(168, 178, 192),
        SceneOrientationFill: Color.FromArgb(218, 25, 31, 39),
        SceneOrientationBorder: Color.FromRgb(90, 105, 122));

    public ResourceDictionary ToResourceDictionary() => new()
    {
        [ThemeResourceBindings.Surface] = Brush(Surface),
        [ThemeResourceBindings.SubtleSurface] = Brush(SubtleSurface),
        [ThemeResourceBindings.Workspace] = Brush(Workspace),
        [ThemeResourceBindings.Border] = Brush(Border),
        [ThemeResourceBindings.TextPrimary] = Brush(TextPrimary),
        [ThemeResourceBindings.TextSecondary] = Brush(TextSecondary),
        [ThemeResourceBindings.TextMuted] = Brush(TextMuted),
        [ThemeResourceBindings.TextDisabled] = Brush(TextDisabled),
        [ThemeResourceBindings.TextAccent] = Brush(TextAccent),
        [ThemeResourceBindings.TextOnAccent] = Brush(TextOnAccent),
        [ThemeResourceBindings.TextWarning] = Brush(TextWarning),
        [ThemeResourceBindings.TextError] = Brush(TextError),
        [ThemeResourceBindings.TextSuccess] = Brush(TextSuccess),
        [ThemeResourceBindings.MutedText] = Brush(TextSecondary),
        [ThemeResourceBindings.Hover] = Brush(Hover),
        [ThemeResourceBindings.HoverBorder] = Brush(HoverBorder),
        [ThemeResourceBindings.RibbonHover] = Brush(RibbonHover),
        [ThemeResourceBindings.RibbonHoverBorder] = Brush(RibbonHoverBorder),
        [ThemeResourceBindings.RibbonTabHover] = Brush(RibbonTabHover),
        [ThemeResourceBindings.PlotBackground] = Brush(PlotBackground),
        [ThemeResourceBindings.PlotText] = Brush(PlotText),
        [ThemeResourceBindings.PlotTick] = Brush(PlotTick),
        [ThemeResourceBindings.PlotGrid] = Brush(PlotGrid),
        [ThemeResourceBindings.PlotAxis] = Brush(PlotAxis),
        [ThemeResourceBindings.PlotZeroLine] = Brush(PlotZeroLine),
        [ThemeResourceBindings.PlotHint] = Brush(PlotHint),
        [ThemeResourceBindings.PlotTooltipBackground] = Brush(PlotTooltipBackground),
        [ThemeResourceBindings.PlotTooltipBorder] = Brush(PlotTooltipBorder),
        [ThemeResourceBindings.PlotHoverMarkerFill] = Brush(PlotHoverMarkerFill),
        [ThemeResourceBindings.PlotBar] = Brush(PlotBar),
        [ThemeResourceBindings.SceneBackground] = Brush(SceneBackground),
        [ThemeResourceBindings.SceneBackgroundAlt] = Brush(SceneBackgroundAlt),
        [ThemeResourceBindings.SceneLensFill] = Brush(SceneLensFill),
        [ThemeResourceBindings.SceneReference] = Brush(SceneReference),
        [ThemeResourceBindings.SceneAxis] = Brush(SceneAxis),
        [ThemeResourceBindings.SceneStop] = Brush(SceneStop),
        [ThemeResourceBindings.SceneApertureStop] = Brush(SceneApertureStop),
        [ThemeResourceBindings.SceneSurface] = Brush(SceneSurface),
        [ThemeResourceBindings.SceneLensEdge] = Brush(SceneLensEdge),
        [ThemeResourceBindings.SceneTarget] = Brush(SceneTarget),
        [ThemeResourceBindings.SceneOrientationFill] = Brush(SceneOrientationFill),
        [ThemeResourceBindings.SceneOrientationBorder] = Brush(SceneOrientationBorder)
    };

    private static SolidColorBrush Brush(Color color) => new(color);
}
